/**
 * The history log.
 *
 * Every attempt, newest first, with the problem itself rebuilt from its id.
 * Storing only the id is what makes this cheap: a year of practice is a few
 * hundred kilobytes, and the problem shown is regenerated by the same code
 * that produced it rather than read from a stale copy.
 *
 * Anything here can be reopened and tried again, which is the point — a wrong
 * answer three days ago is the most useful thing in the log.
 */

import { useMemo, useState } from 'react';
import { getSkill } from './../curriculum/skills.ts';
import { problemFromId } from './../curriculum/registry.ts';
import type { Problem } from './../curriculum/types.ts';
import type { Attempt } from './../mastery/model.ts';
import { toLatex } from './../engine/print.ts';
import { MathView } from './MathView.tsx';
import type { Learner } from './useLearner.ts';

type Filter = 'all' | 'wrong' | 'hinted' | 'clean';

export function HistoryView({ learner, onRetry }: {
  learner: Learner;
  onRetry: (skillId: string) => void;
}) {
  const [filter, setFilter] = useState<Filter>('all');
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = useMemo(() => {
    switch (filter) {
      case 'wrong': return learner.attempts.filter((a) => !a.correct);
      case 'hinted': return learner.attempts.filter((a) => a.correct && a.hintLevel >= 0);
      case 'clean': return learner.attempts.filter((a) => a.correct && a.hintLevel < 0 && a.wrongTries === 0);
      default: return learner.attempts;
    }
  }, [learner.attempts, filter]);

  const byDay = useMemo(() => groupByDay(filtered), [filtered]);

  const totals = useMemo(() => {
    const all = learner.attempts;
    return {
      total: all.length,
      correct: all.filter((a) => a.correct).length,
      seconds: all.reduce((s, a) => s + a.seconds, 0),
      days: new Set(all.map((a) => dayKey(a.at))).size,
    };
  }, [learner.attempts]);

  if (!learner.ready) return <div className="page"><p className="muted">Loading…</p></div>;

  if (learner.attempts.length === 0) {
    return (
      <div className="page">
        <h1>History</h1>
        <div className="empty">
          <div className="empty__glyph">◷</div>
          <h2>Nothing logged yet</h2>
          <p className="muted">Every problem you answer shows up here, and can be reopened.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <h1>History</h1>
      <p className="subtitle">
        {totals.total} problems over {totals.days} day{totals.days === 1 ? '' : 's'},
        {' '}{Math.round((totals.correct / totals.total) * 100)}% right, {formatSpent(totals.seconds)} spent.
      </p>

      <div className="row row--wrap" style={{ gap: 7, marginBottom: 16 }}>
        {([
          ['all', 'Everything'],
          ['wrong', 'Missed'],
          ['hinted', 'Needed a hint'],
          ['clean', 'First time'],
        ] as Array<[Filter, string]>).map(([id, label]) => (
          <button
            key={id}
            className={`btn btn--sm ${filter === id ? 'btn--primary' : ''}`}
            onClick={() => setFilter(id)}
          >
            {label}
          </button>
        ))}
      </div>

      {byDay.length === 0 && (
        <div className="empty"><p className="muted">Nothing matches that filter.</p></div>
      )}

      {byDay.map(([day, attempts]) => (
        <section key={day} style={{ marginBottom: 22 }}>
          <div className="eyebrow" style={{ marginBottom: 8 }}>{formatDay(day)}</div>
          <div className="card card--flush">
            {attempts.map((a, i) => (
              <HistoryRow
                key={`${a.at}-${i}`}
                attempt={a}
                open={expanded === `${a.at}-${i}`}
                onToggle={() => setExpanded(expanded === `${a.at}-${i}` ? null : `${a.at}-${i}`)}
                onRetry={onRetry}
              />
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}

function HistoryRow({ attempt, open, onToggle, onRetry }: {
  attempt: Attempt;
  open: boolean;
  onToggle: () => void;
  onRetry: (skillId: string) => void;
}) {
  const skill = getSkill(attempt.skillId);
  // Rebuilt on demand, and only when opened: regenerating every row would
  // make a long log slow for no reason.
  const problem = useMemo<Problem | null>(() => {
    if (!open) return null;
    try {
      return problemFromId(attempt.problemId);
    } catch {
      return null;
    }
  }, [open, attempt.problemId]);

  const mark = attempt.correct
    ? (attempt.hintLevel >= 0 || attempt.wrongTries > 0 ? '◐' : '✓')
    : '✗';
  const markColour = attempt.correct
    ? (attempt.hintLevel >= 0 || attempt.wrongTries > 0 ? 'var(--partial)' : 'var(--correct)')
    : 'var(--wrong)';

  return (
    <div style={{ borderBottom: '1px solid var(--border)' }}>
      <button
        onClick={onToggle}
        aria-expanded={open}
        style={{
          width: '100%', background: 'none', border: 0, textAlign: 'left',
          padding: '11px 15px', cursor: 'pointer', display: 'flex',
          alignItems: 'center', gap: 12, minHeight: 'var(--tap)', color: 'inherit',
        }}
      >
        <span style={{ color: markColour, fontSize: 16, flex: 'none', width: 16 }}>{mark}</span>
        <span style={{ flex: 1, minWidth: 0 }}>
          <span style={{ display: 'block', fontSize: 14.5 }}>{skill?.name ?? attempt.skillId}</span>
          <span className="small faint">
            {formatTime(attempt.at)} · {attempt.seconds}s
            {attempt.hintLevel >= 0 && ` · ${attempt.hintLevel >= 4 ? 'saw the solution' : 'used a hint'}`}
            {attempt.wrongTries > 0 && ` · ${attempt.wrongTries} wrong ${attempt.wrongTries === 1 ? 'try' : 'tries'}`}
          </span>
        </span>
        <span className="faint" style={{ flex: 'none' }}>{open ? '▴' : '▾'}</span>
      </button>

      {open && (
        <div style={{ padding: '0 15px 14px 43px' }}>
          {problem ? (
            <>
              <div className="small muted" style={{ marginBottom: 5 }}>{problem.prompt}</div>
              <MathView latex={toLatex(problem.statement)} />
              <div className="small faint" style={{ margin: '8px 0 10px' }}>
                Answer: <MathView latex={answerLatex(problem)} size="sm" />
              </div>
              <button className="btn btn--sm" onClick={() => onRetry(attempt.skillId)}>
                Practise this topic
              </button>
            </>
          ) : (
            <p className="small faint" style={{ margin: 0 }}>
              This problem could not be rebuilt — it was made by an older version of the app.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function answerLatex(problem: Problem): string {
  const spec = problem.answer;
  switch (spec.kind) {
    case 'expression': case 'simplified': case 'number':
      return toLatex(spec.value);
    case 'set':
      return spec.values.map((v) => toLatex(v)).join(', \; ');
    case 'tuple':
      return spec.values.map((v, i) => `${spec.labels?.[i] ?? ''} = ${toLatex(v)}`).join(', \; ');
    case 'choice':
      return `\\text{${spec.options[spec.correct] ?? ''}}`;
    case 'special':
      return spec.value === 'no-solution' ? '\\text{no solution}' : '\\text{every value}';
  }
}

/** Time spent, in whatever unit does not read as zero. */
function formatSpent(seconds: number): string {
  if (seconds < 90) return `${Math.max(1, Math.round(seconds))} seconds`;
  if (seconds < 5400) return `${Math.round(seconds / 60)} minutes`;
  const hours = seconds / 3600;
  return `${hours.toFixed(hours < 10 ? 1 : 0)} hours`;
}

const dayKey = (at: number): string => new Date(at).toISOString().slice(0, 10);

function groupByDay(attempts: readonly Attempt[]): Array<[string, Attempt[]]> {
  const map = new Map<string, Attempt[]>();
  for (const a of attempts) {
    const k = dayKey(a.at);
    const list = map.get(k) ?? [];
    list.push(a);
    map.set(k, list);
  }
  return [...map.entries()].sort((a, b) => (a[0] < b[0] ? 1 : -1));
}

function formatDay(key: string): string {
  const today = dayKey(Date.now());
  const yesterday = dayKey(Date.now() - 86_400_000);
  if (key === today) return 'Today';
  if (key === yesterday) return 'Yesterday';
  return new Date(`${key}T12:00:00`).toLocaleDateString(undefined, {
    weekday: 'long', day: 'numeric', month: 'long',
  });
}

const formatTime = (at: number): string =>
  new Date(at).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
